name: trade_companion
description: A companion app for Python Trading Engine.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  dio: ^5.3.0
  
  # State Management
  flutter_riverpod: ^2.4.0
  
  # Routing
  go_router: ^12.0.0
  
  # Utils
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  uuid: ^4.2.2
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#121212"
  image: "assets/splash/splash_logo.png"
  android_12:
    color: "#121212"
    image: "assets/splash/splash_logo.png"
  web: false
